{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "maven-hello-world.fullname" . }}
  labels:
    {{- include "maven-hello-world.labels" . | nindent 4 }}
{{- end }}
