apiVersion: v1
kind: Service
metadata:
  name: {{ include "maven-hello-world.fullname" . }}
  labels:
    {{- include "maven-hello-world.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "LoadBalancer" }}
  ports:
    - port: {{ .Values.service.port | default 80 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "maven-hello-world.selectorLabels" . | nindent 4 }}
